<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Asus ROG Zephyrus G14',
                'brand' => 'ASUS',
                'description' => 'Laptop gaming ultraportable 14 inci terbaik dengan prosesor AMD Ryzen 9 dan NVIDIA RTX 4060, layar ROG Nebula HDR, dan desain ringkas premium.',
                'processor' => 'AMD Ryzen 9 8945HS',
                'ram' => 16,
                'storage' => 1024,
                'graphic_card' => 'NVIDIA GeForce RTX 4060 (8GB)',
                'screen_size' => 14.0,
                'price' => 28999000,
                'is_active' => true,
                'sold' => 55,
            ],
            [
                'name' => 'Apple MacBook Air M3',
                'brand' => 'Apple',
                'description' => 'Laptop tertipis dan teringan dari Apple kini dengan chip M3 yang super cepat, baterai tahan hingga 18 jam, dan layar Liquid Retina yang memukau.',
                'processor' => 'Apple M3 Chip (8-Core CPU)',
                'ram' => 16,
                'storage' => 512,
                'graphic_card' => 'Apple M3 Integrated GPU',
                'screen_size' => 13.6,
                'price' => 17499000,
                'is_active' => true,
                'sold' => 110,
            ],
            [
                'name' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'brand' => 'Lenovo',
                'description' => 'Laptop bisnis legendaris kelas enterprise dengan sasis serat karbon yang ringan dan kokoh, keyboard terbaik di industri, serta fitur keamanan tingkat tinggi.',
                'processor' => 'Intel Core i7-1355U',
                'ram' => 16,
                'storage' => 1024,
                'graphic_card' => 'Intel Iris Xe Graphics',
                'screen_size' => 14.0,
                'price' => 24500000,
                'is_active' => true,
                'sold' => 35,
            ],
            [
                'name' => 'HP Pavilion 14',
                'brand' => 'HP',
                'description' => 'Laptop harian serbaguna yang handal dengan prosesor Intel Core i5, RAM 16GB, penyimpanan SSD cepat, cocok untuk pelajar dan pekerja kantoran.',
                'processor' => 'Intel Core i5-1335U',
                'ram' => 16,
                'storage' => 512,
                'graphic_card' => 'Intel Iris Xe Graphics',
                'screen_size' => 14.0,
                'price' => 9499000,
                'is_active' => true,
                'sold' => 80,
            ],
            [
                'name' => 'Dell XPS 13',
                'brand' => 'Dell',
                'description' => 'Laptop ultrabook premium dengan layar InfinityEdge 4K bezel-less, performa kencang dengan Intel Evo, dan material aluminium CNC yang mewah.',
                'processor' => 'Intel Core i7-1250U',
                'ram' => 16,
                'storage' => 512,
                'graphic_card' => 'Intel Iris Xe Graphics',
                'screen_size' => 13.4,
                'price' => 21999000,
                'is_active' => true,
                'sold' => 20,
            ],
            [
                'name' => 'Acer Swift Go 14',
                'brand' => 'Acer',
                'description' => 'Laptop tipis stylish dengan layar OLED 2.8K yang tajam dan akurat, ditenagai prosesor Intel Core Ultra terbaru berkemampuan AI.',
                'processor' => 'Intel Core Ultra 5 125H',
                'ram' => 16,
                'storage' => 512,
                'graphic_card' => 'Intel Arc Graphics',
                'screen_size' => 14.0,
                'price' => 11999000,
                'is_active' => true,
                'sold' => 60,
            ],
            [
                'name' => 'Lenovo Legion Slim 5',
                'brand' => 'Lenovo',
                'description' => 'Laptop gaming bertenaga dengan sistem pendingin Legion Coldfront 5.0, performa tinggi untuk gaming AAA dan rendering 3D.',
                'processor' => 'AMD Ryzen 7 7840HS',
                'ram' => 16,
                'storage' => 512,
                'graphic_card' => 'NVIDIA GeForce RTX 4050 (6GB)',
                'screen_size' => 16.0,
                'price' => 18499000,
                'is_active' => true,
                'sold' => 85,
            ],
            [
                'name' => 'MSI Prestige 14 Evo',
                'brand' => 'MSI',
                'description' => 'Laptop bisnis dan kreator konten bersertifikasi Intel Evo, tipis, ringan, dengan daya tahan baterai luar biasa dan warna layar yang presisi.',
                'processor' => 'Intel Core i7-13700H',
                'ram' => 16,
                'storage' => 1024,
                'graphic_card' => 'Intel Iris Xe Graphics',
                'screen_size' => 14.0,
                'price' => 15999000,
                'is_active' => true,
                'sold' => 45,
            ],
            [
                'name' => 'Asus Vivobook Go 14',
                'brand' => 'ASUS',
                'description' => 'Laptop belajar dan harian dengan harga sangat terjangkau, bodi tangguh bersertifikasi militer, dan bobot yang sangat ringan untuk mobilitas tinggi.',
                'processor' => 'AMD Ryzen 3 7320U',
                'ram' => 8,
                'storage' => 256,
                'graphic_card' => 'AMD Radeon Graphics',
                'screen_size' => 14.0,
                'price' => 5899000,
                'is_active' => true,
                'sold' => 150,
            ],
            [
                'name' => 'HP Omen 16',
                'brand' => 'HP',
                'description' => 'Laptop gaming flagship dengan layar refresh rate tinggi 165Hz, keyboard RGB backlighting, dan performa monster siap melibas semua game berat.',
                'processor' => 'Intel Core i7-13700HX',
                'ram' => 32,
                'storage' => 1024,
                'graphic_card' => 'NVIDIA GeForce RTX 4060 (8GB)',
                'screen_size' => 16.1,
                'price' => 23499000,
                'is_active' => true,
                'sold' => 25,
            ],
            [
                'name' => 'Apple MacBook Pro 14 M3 Pro',
                'brand' => 'Apple',
                'description' => 'Laptop stasiun kerja profesional untuk kreator, developer, dan editor video. Ditenagai chip M3 Pro dengan efisiensi energi terbaik di dunia.',
                'processor' => 'Apple M3 Pro Chip (11-Core CPU)',
                'ram' => 18,
                'storage' => 512,
                'graphic_card' => 'Apple M3 Pro Integrated GPU',
                'screen_size' => 14.2,
                'price' => 32999000,
                'is_active' => true,
                'sold' => 65,
            ],
            [
                'name' => 'Lenovo IdeaPad Slim 3',
                'brand' => 'Lenovo',
                'description' => 'Laptop entry-level serbaguna berkinerja solid untuk produktivitas harian, browsing, dan kelas online. Dilengkapi privacy shutter pada webcam.',
                'processor' => 'Intel Core i3-1215U',
                'ram' => 8,
                'storage' => 512,
                'graphic_card' => 'Intel UHD Graphics',
                'screen_size' => 14.0,
                'price' => 6799000,
                'is_active' => true,
                'sold' => 95,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
